合并不同环境 workflow

diff --git a/.github/workflows/run-tqsdk.yml b/.github/workflows/run-tqsdk.yml
--- a/.github/workflows/run-tqsdk.yml
+++ b/.github/workflows/run-tqsdk.yml
@@ -1,15 +1,65 @@
-name: Test and Deploy(Linux-py3.6-x64)
+name: CI for tqsdk-python-private
 
 on:
   repository_dispatch:
-    types: [linux-py3.6-x64*]
+    types: [run-ci-*]
 
 jobs:
+  setup:
+    name: log the workflow url in src repo in pr comment
+    runs-on: ubuntu-latest
+    steps:
+    - name: Dump GitHub context
+      env:
+        GITHUB_CONTEXT: ${{ toJson(github) }}
+      run: echo "$GITHUB_CONTEXT"
+
+    - name: Add comment show workflow url
+      uses: peter-evans/create-or-update-comment@v1
+      with:
+        token: ${{ secrets.GH_PAT }}
+        repository: shinnytech/tqsdk-python-private
+        issue-number: ${{ github.event.client_payload.pr_number }}
+        comment-id: ${{ github.event.client_payload.comment_id }}
+        body: |
+          - Workflow url: https://github.com/shinnytech/tqsdk-python-private/actions/runs/${{ github.run_id }}
+
+    - name: Checkout
+      uses: actions/checkout@v2
+      with:
+        repository: shinnytech/tqsdk-python-private
+        ref: ${{ github.event.client_payload.ref }}
+        token: ${{ secrets.GH_PAT }}
+
+    - name: Giant Files List
+      id: giant-files-list
+      run: |
+        git ls-files | xargs ls -l | sort -nrk5 | awk '{if($5 > ${{ secrets.FILE_LIMIT_SIZE }}) print $9 }' | xargs ls -lrth
+        echo "::set-output name=GIANT-FILES-COUNT::$(git ls-files | xargs ls -l | sort -nrk5 | awk '{if($5 > ${{ secrets.FILE_LIMIT_SIZE }}) print $0}' | wc -l)"
+
+    - name: Giant Files Check
+      if: steps.giant-files-list.outputs.GIANT-FILES-COUNT != 0
+      run: |
+        echo "files size check failed"
+        exit 1
+
   test:
+    needs: setup
     strategy:
       matrix:
         envinfo:
           - { name: 'linux-3.6-x64', os: ubuntu-latest, python-version: 3.6.x, python-arch: x64, TZ: 'Asia/Shanghai' }
+          - { name: 'linux-3.7-x64', os: ubuntu-latest, python-version: 3.7.x, python-arch: x64, TZ: 'Asia/Shanghai' }
+          - { name: 'linux-3.8-x64', os: ubuntu-latest, python-version: 3.8.x, python-arch: x64, TZ: 'Asia/Shanghai' }
+          - { name: 'macos-3.6-x64', os: macos-latest, python-version: 3.6.x, python-arch: x64, TZ: 'Asia/Shanghai' }
+          - { name: 'macos-3.7-x64', os: macos-latest, python-version: 3.7.x, python-arch: x64, TZ: 'Asia/Shanghai' }
+          - { name: 'macos-3.8-x64', os: macos-latest, python-version: 3.8.x, python-arch: x64, TZ: 'Asia/Shanghai' }
+          - { name: 'windows-3.6-x64', os: windows-latest, python-version: 3.6.x, python-arch: x64, TZ: 'CST-8' }
+          - { name: 'windows-3.6-x86', os: windows-latest, python-version: 3.6.x, python-arch: x86, TZ: 'CST-8' }
+          - { name: 'windows-3.7-x64', os: windows-latest, python-version: 3.7.x, python-arch: x64, TZ: 'CST-8' }
+          - { name: 'windows-3.7-x86', os: windows-latest, python-version: 3.7.x, python-arch: x86, TZ: 'CST-8' }
+          - { name: 'windows-3.8-x64', os: windows-latest, python-version: 3.8.x, python-arch: x64, TZ: 'CST-8' }
+          - { name: 'windows-3.8-x86', os: windows-latest, python-version: 3.8.x, python-arch: x86, TZ: 'CST-8' }
 
     env:
         PYTHONIOENCODING: "utf-8"
@@ -26,19 +76,7 @@ jobs:
       with:
         repository: shinnytech/tqsdk-python-private
         ref: ${{ github.event.client_payload.ref }}
-        token: ${{ secrets.TQSDKCI }}
-
-    - name: Giant Files List
-      id: giant-files-list
-      run: |
-        git ls-files | xargs ls -l | sort -nrk5 | awk '{if($5 > ${{ secrets.FILE_LIMIT_SIZE }}) print $9 }' | xargs ls -lrth
-        echo "::set-output name=GIANT-FILES-COUNT::$(git ls-files | xargs ls -l | sort -nrk5 | awk '{if($5 > ${{ secrets.FILE_LIMIT_SIZE }}) print $0}' | wc -l)"
-
-    - name: Giant Files Check
-      if: steps.giant-files-list.outputs.GIANT-FILES-COUNT != 0
-      run: |
-        echo "files size check failed"
-        exit 1
+        token: ${{ secrets.GH_PAT }}
 
     - name: Setup Node.js 12.x
       uses: actions/setup-node@v1
@@ -100,7 +138,7 @@ jobs:
       with:
         repository: shinnytech/tqsdk-python-private
         ref: ${{ github.event.client_payload.ref }}
-        token: ${{ secrets.TQSDKCI }}
+        token: ${{ secrets.GH_PAT }}
 
     - name: Setup Node.js 12.x
       uses: actions/setup-node@v1
@@ -143,38 +181,11 @@ jobs:
         rm -rf build
         sphinx-build doc build/doc
 
-    - name: Publish to pypi
-      if: startsWith(github.event.ref, 'refs/tags')
-      uses: pypa/gh-action-pypi-publish@master
-      with:
-        user: __token__
-        password: ${{ secrets.PYPI_PASSWORD }}
-
-    - name: Publish to github release
-      if: startsWith(github.event.ref, 'refs/tags')
-      uses: fnkr/github-action-ghr@v1
-      env:
-        GHR_PATH: dist/
-        GITHUB_TOKEN: ${{ secrets.GITHUB_USER_TOKEN }}
-
     - name: Setup AWS S3 dist path
-      if: startsWith(github.event.ref, 'refs/heads')
       shell: bash
       run: |
-        echo "::set-env name=DIST_DIR::dist/tqsdk-python/$(echo ${GITHUB_REF#refs/heads/})/$(date -d today +%Y%m%d)_$(echo ${GITHUB_SHA:0:7})/"
-        echo "::set-env name=DOC_DIR::docs/tqsdk-python/$(echo ${GITHUB_REF#refs/heads/})/"
-
-    - name: Setup AWS S3 dist path on tag
-      if: startsWith(github.event.ref, 'refs/tags')
-      shell: bash
-      run: |
-        echo "::set-env name=DIST_DIR::dist/tqsdk-python/$(echo ${GITHUB_REF#refs/tags/})/"
-        echo "::set-env name=DOC_DIR::docs/tqsdk-python/$(echo ${GITHUB_REF#refs/tags/})/"
-
-    - name: Setup AWS S3 dist path on pull_request
-      if: github.event_name == 'pull_request'
-      run: |
-        echo "::set-env name=DIST_DIR::dist/tqsdk-python/pr-${{ github.event.number }}/"
+        echo "::set-env name=DIST_DIR::dist/tqsdk-python-private/$(echo ${{ github.event.client_payload.ref }})/$(date -d today +%Y%m%d)_$(echo ${{ github.event.client_payload.sha }})/"
+        echo "::set-env name=DOC_DIR::docs/tqsdk-python-private/$(echo ${{ github.event.client_payload.ref }})/"
 
     - name: Publish dist to AWS S3
       uses: jakejarvis/s3-sync-action@master
@@ -187,7 +198,6 @@ jobs:
         DEST_DIR: ${{ env.DIST_DIR }}
 
     - name: Publish tag build/doc to AWS S3
-      if: github.event_name != 'pull_request'
       uses: jakejarvis/s3-sync-action@master
       with:
         args: --exclude '.doctrees/*'
@@ -199,12 +209,27 @@ jobs:
         SOURCE_DIR: "build/doc"
         DEST_DIR: ${{ env.DOC_DIR }}
 
-    - name: Create commit comment
-      if: success() and ${{ github.event.client_payload.pr }}
-      uses: peter-evans/commit-comment@v1
+  summary:
+    name: summary CI result
+    needs: deploy
+    runs-on: ubuntu-latest
+    steps:
+    - name: Find Comment
+      uses: peter-evans/find-comment@v1
+      id: fc
       with:
-        token: ${{ secrets.TQSDKCI }}
         repository: shinnytech/tqsdk-python-private
-        sha: ${{ github.event.client_payload.pr }}
-        body: linux py3.6 x64 run ci success ${{ github.event.client_payload.title }}
-        position: 1
+        token: ${{ secrets.GH_PAT }}
+        issue-number: ${{ github.event.client_payload.pr_number }}
+        body-includes:  https://github.com/shinnytech/tqsdk-python-private/actions/runs/${{ github.run_id }}
+
+    - name: Add comment show success
+      uses: peter-evans/create-or-update-comment@v1
+      with:
+        token: ${{ secrets.GH_PAT }}
+        repository: shinnytech/tqsdk-python-private
+        issue-number: ${{ github.event.client_payload.pr_number }}
+        comment-id: ${{ steps.fc.outputs.comment-id }}
+        body: |
+          workflow ${{ github.run_id }} run success!
+        reactions: '+1'
